use_frameworks!

platform :ios, '10.0'

target 'ShopifyCheckoutSheetKit_Example' do
  pod 'ShopifyCheckoutSheetKit', :path => '../'

  target 'ShopifyCheckoutSheetKit_Tests' do
    inherit! :search_paths

    
  end
end
